<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\SpecialistDoctorInDepartment\**" />
    <EmbeddedResource Remove="Features\SpecialistDoctorInDepartment\**" />
    <None Remove="Features\SpecialistDoctorInDepartment\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EliteCare.Service\EliteCare.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Appointments\Commands\Validations\" />
    <Folder Include="Features\Departments\Commands\Validations\" />
    <Folder Include="Features\patients\Commands\Validations\" />
    <Folder Include="Features\patients\Queries\Response\" />
    <Folder Include="Features\Receptionists\Commands\Validations\" />
    <Folder Include="Features\test\Commands\Handlers\" />
    <Folder Include="Features\test\Commands\Models\" />
    <Folder Include="Features\test\Commands\Validations\" />
    <Folder Include="Features\test\Queries\Handlers\" />
    <Folder Include="Features\test\Queries\Models\" />
    <Folder Include="Features\test\Queries\Response\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
  </ItemGroup>

</Project>
